export * from './registry';
export { DashboardPage } from './dashboard/dashboard-page';
export { ReceptionPage } from './reception';
export { WaiterPage } from './waiter';
export { KitchenPage } from './kitchen';
export { TablePage } from './table';
export { CustomerPage } from './customer';
export { CashierPage } from './cashier';
export { AdminPage } from './admin';
export { TvPickupPage } from './tv-pickup/tv-pickup-page';
export { DeliveryPage } from './delivery/delivery-page';
