import { StaffRole } from './role';
import { Permission } from './permission';

// Role-based permission matrix
// Each role gets a set of base permissions
export const ROLE_PERMISSIONS: Record<StaffRole, Permission[]> = {
  [StaffRole.ADMIN]: [
    Permission.RESTAURANT_MANAGE,
    Permission.STAFF_MANAGE,
    Permission.STAFF_READ,
    Permission.CUSTOMER_MANAGE,
    Permission.ANALYTICS_READ,
    Permission.EVENTS_READ,
    // Admin implicitly has all operational permissions too
    Permission.WAITLIST_READ,
    Permission.WAITLIST_MANAGE,
    Permission.TABLES_READ,
    Permission.TABLES_ASSIGN,
    Permission.TABLES_OCCUPY,
    Permission.TABLES_RELEASE,
    Permission.TABLE_DEVICES_READ,
    Permission.TABLE_DEVICES_MANAGE,
    Permission.TABLE_SESSIONS_READ,
    Permission.TABLE_SESSIONS_MANAGE,
    Permission.TABLE_SESSIONS_CHANGE_WAITER,
    Permission.ORDERS_READ,
    Permission.ORDERS_CREATE,
    Permission.ORDERS_UPDATE,
    Permission.ORDERS_SEND_TO_KITCHEN,
    Permission.ORDERS_DELIVER,
    Permission.PREORDERS_READ,
    Permission.PREORDERS_CREATE,
    Permission.PREORDERS_UPDATE,
    Permission.KITCHEN_ORDERS_READ,
    Permission.KITCHEN_ORDERS_START,
    Permission.KITCHEN_ORDERS_READY,
    Permission.KITCHEN_ORDERS_COMPLETE,
    Permission.KITCHEN_ORDERS_ASSIGN,
    Permission.ACCOUNTS_READ,
    Permission.ACCOUNTS_REQUEST_PAYMENT,
    Permission.ACCOUNTS_CLOSE,
    Permission.PAYMENTS_REGISTER,
    Permission.PAYMENTS_READ,
    Permission.CATALOG_READ,
    Permission.CATALOG_MANAGE,
    Permission.REVIEWS_READ,
    Permission.REVIEWS_MANAGE,
    Permission.SERVICE_TASKS_READ,
    Permission.SERVICE_TASKS_MANAGE,
  ],
  [StaffRole.RECEPTIONIST]: [
    Permission.WAITLIST_READ,
    Permission.WAITLIST_MANAGE,
    Permission.TABLES_READ,
    Permission.TABLES_ASSIGN,
    Permission.TABLES_OCCUPY,
    Permission.TABLES_RELEASE,
    Permission.TABLE_DEVICES_READ,
    Permission.TABLE_DEVICES_MANAGE,
    Permission.TABLE_SESSIONS_READ,
    Permission.TABLE_SESSIONS_MANAGE,
    Permission.TABLE_SESSIONS_CHANGE_WAITER,
    Permission.CUSTOMER_MANAGE,
    Permission.STAFF_READ,
    Permission.CATALOG_READ,
  ],
  [StaffRole.WAITER]: [
    Permission.TABLES_READ,
    Permission.TABLE_SESSIONS_READ,
    Permission.TABLE_SESSIONS_MANAGE,
    Permission.TABLE_SESSIONS_CHANGE_WAITER,
    Permission.ORDERS_READ,
    Permission.ORDERS_CREATE,
    Permission.ORDERS_UPDATE,
    Permission.ORDERS_SEND_TO_KITCHEN,
    Permission.ORDERS_DELIVER,
    Permission.PREORDERS_READ,
    Permission.PREORDERS_CREATE,
    Permission.PREORDERS_UPDATE,
    Permission.ACCOUNTS_READ,
    Permission.ACCOUNTS_REQUEST_PAYMENT,
    Permission.SERVICE_TASKS_READ,
    Permission.SERVICE_TASKS_MANAGE,
    Permission.REVIEWS_READ,
    Permission.STAFF_READ,
    Permission.CATALOG_READ,
  ],
  [StaffRole.KITCHEN]: [
    Permission.KITCHEN_ORDERS_READ,
    Permission.KITCHEN_ORDERS_START,
    Permission.KITCHEN_ORDERS_READY,
    Permission.KITCHEN_ORDERS_COMPLETE,
    Permission.ORDERS_READ,
    Permission.SERVICE_TASKS_READ,
  ],
  [StaffRole.CASHIER]: [
    Permission.ACCOUNTS_READ,
    Permission.ACCOUNTS_REQUEST_PAYMENT,
    Permission.ACCOUNTS_CLOSE,
    Permission.PAYMENTS_REGISTER,
    Permission.PAYMENTS_READ,
    Permission.ORDERS_READ,
    Permission.TABLE_SESSIONS_READ,
    Permission.SERVICE_TASKS_READ,
  ],
};

// Customer permissions (independent of staff roles)
export const CUSTOMER_PERMISSIONS: Permission[] = [
  Permission.PREORDERS_READ,
  Permission.PREORDERS_CREATE,
  Permission.PREORDERS_UPDATE,
  Permission.ORDERS_READ,
  Permission.ORDERS_CREATE,
  Permission.SERVICE_TASKS_READ,
  Permission.SERVICE_TASKS_MANAGE,
  Permission.REVIEWS_CREATE,
  Permission.REVIEWS_READ,
];
